### ISSUE TITLE
WTF is .DS_Store

### ISSUE THREAD

**Issue by gracegeddes** [gracegeddes/IknowSomewhere#1]
@AlexTB411 please resolve what this file is and why it was commited

**Comment by AlexTB411** [comment]
Did I commit it originally? Cos I got no idea what it is

**Comment by gracegeddes** [comment]
Yes it was you. You've been assigned the task of figuring out what it is

**Comment by AlexTB411** [comment]
Is this your manager voice cos i feel ordered and attacked

**Comment by gracegeddes** [comment]
Lol yes, I was writing emails at the same time as this

**Comment by AlexTB411** [comment]
Lol I’d watch out cos it can come across as a bit rude

**Comment by gracegeddes** [comment]
Nah, it's an auditor way of speaking. No room for negotiation, give me the evidence.

**Comment by gracegeddes** [comment]
@rcushen
